FROM envoyproxy/envoy:v1.37-latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends gettext-base ca-certificates && rm -rf /var/lib/apt/lists/*

COPY ./deploy/envoy/envoy.yaml.tmpl /etc/envoy/envoy.yaml.tmpl
COPY ./deploy/envoy/entrypoint.envoy.sh /entrypoint.envoy.sh
RUN chmod +x /entrypoint.envoy.sh

EXPOSE 8080 9901

ENTRYPOINT ["/entrypoint.envoy.sh"]
